### ISSUE TITLE
Failed tests after switch to gcc-7 in new bionic GAP 4.9.1 container

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/gap-docker#18]
The build at https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9/builds/387912434 is made with the new GAP 4.9.1 container which has gcc-7 as a default compiler.

The following packages which used to pass tests now fail. The tick box means that the problem has been fixed).

- [x] cvec - fixed
- [x] fining - resolved by fixing cvec
- [x] cryst - reported in https://github.com/gap-packages/cryst/issues/7
- [x] fr - reported in https://github.com/gap-packages/fr/issues/26
- [x] nq - see https://github.com/gap-packages/nq/issues/3, https://github.com/gap-system/gap/issues/2513 and https://github.com/gap-packages/lpres/issues/11.
- [x] sgpviz - reported at https://github.com/gap-packages/sgpviz/issues/3
- [x] xmodalg - reported at https://github.com/gap-packages/xmodalg/issues/24

In more details below.

1. cvec - see https://github.com/gap-packages/cvec/issues/6 

2. fining - the problem disappears if cvec is fixed as suggested in https://github.com/gap-packages/cvec/issues/6 

3. cryst - only when all packages are loaded:
```
testing: /home/gap/inst/gap-4.9.1/pkg/cryst/tst/cryst.tst
########> Diff in /home/gap/inst/gap-4.9.1/pkg/cryst/tst/cryst.tst:175
# Input is:
g := PreImage(iso, h);
# Expected output:
[ [ 1, 0, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, -1, 0, 0 ], [ -7/4, 5/4, 3/4, 1 ] ]
# But found:
[ [ 0, -1, 0, 0 ], [ -1, 0, 0, 0 ], [ 0, 0, -1, 0 ], [ -1/4, 3/4, 3/4, 1 ] ]
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/cryst/tst/cryst.tst:314
# Input is:
NaturalHomomorphismByNormalSubgroup( G, K );
# Expected output:
CompositionMapping( [ g1, g2, g3, g4, g5, g6, g7 ] -> 
[ g1, g2, g3, g4, id, id, id ], 
[ [ [ 1, 0, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, -1, 0, 0 ], [ -7/4, 5/4, 3/4, 1 ] ]
    , [ [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 1, 0, 0, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, -1, 0, 0 ], [ 0, 0, -1, 0 ], [ -1/2, -1/2, 1, 1 ] ]
    , 
  [ [ -1, 0, 0, 0 ], [ 0, -1, 0, 0 ], [ 0, 0, 1, 0 ], [ 1/2, 0, -1/2, 1 ] ],
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 1/2, 1/2, 1/2, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 1, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 1, 1 ] ] ] -> 
[ g1, g2, g3, g4, g5, g6, g7 ] )

# But found:
CompositionMapping( [ g1, g2, g3, g4, g8, g5, g6, g7, g8^2, g9, g10 ] -> 
[ g1, g2, g3, g4, g5, id, id, id, id, id, id ], 
[ [ [ 0, -1, 0, 0 ], [ -1, 0, 0, 0 ], [ 0, 0, -1, 0 ], [ -1/4, 3/4, 3/4, 1 ] ]
    , [ [ 0, 0, 1, 0 ], [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 3, -2, 1, 1 ] ], 
  [ [ -1, 0, 0, 0 ], [ 0, -1, 0, 0 ], [ 0, 0, 1, 0 ], [ -7/2, 0, -3/2, 1 ] ], 
  [ [ -1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, -1, 0 ], [ 0, -3/2, -7/2, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 1, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 1, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 1, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ -3/2, -3/2, -3/2, 1 ] ],
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, -3, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ -3, 0, 0, 1 ] ] ] -> 
[ g1, g2, g3, g4, g5, g6, g7, g8, g9, g10 ] )
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/cryst/tst/cryst.tst:330
# Input is:
NaturalHomomorphismByNormalSubgroup( G, K );
# Expected output:
CompositionMapping( [ g1, g2, g3, g4, g5, g6, g7, g8 ] -> 
[ g1, g2, g3, g4, g5, id, id, id ], 
[ [ [ -1, 0, 0, 0 ], [ 0, 1, 0, 1/2 ], [ 0, 0, 1, 1/2 ], [ 0, 0, 0, 1 ] ], 
  [ [ 0, 0, 1, 0 ], [ 0, 1, 0, 0 ], [ -1, 0, 0, 1/2 ], [ 0, 0, 0, 1 ] ], 
  [ [ 0, 0, 1, 0 ], [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ -1, 0, 0, 1/2 ], [ 0, 1, 0, 0 ], [ 0, 0, -1, 1/2 ], [ 0, 0, 0, 1 ] ], 
  [ [ -1, 0, 0, 1/2 ], [ 0, -1, 0, 1/2 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 1 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 1 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 1 ], [ 0, 0, 0, 1 ] ] ] -> 
[ g1, g2, g3, g4, g5, g6, g7, g8 ] )

# But found:
CompositionMapping( [ g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11 ] -> 
[ g1, g2, g3, g4, g5, id, id, id, id, id, id ], 
[ [ [ 0, -1, 0, 1/2 ], [ -1, 0, 0, 1/2 ], [ 0, 0, -1, 1/2 ], [ 0, 0, 0, 1 ] ],
  [ [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 1, 0, 0, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ -1, 0, 0, 1/2 ], [ 0, -1, 0, 1/2 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, -1, 0, 1/2 ], [ 0, 0, -1, 1/2 ], [ 0, 0, 0, 1 ] ], 
  [ [ -1, 0, 0, 0 ], [ 0, -1, 0, 0 ], [ 0, 0, -1, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 1 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 1 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 1 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 3 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 3 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 3 ], [ 0, 0, 0, 1 ] ] ] -> 
[ g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11 ] )
########
```

4. FR - only when all packages are loaded. Not yet clear what triggers this.
```
########> Diff in /home/gap/inst/gap-4.9.1/pkg/fr-2.4.5/tst/cp.tst:67
# Input is:
IsConjugate(GrigorchukGroup,pairs[1][1][1],pairs[1][1][2]);
# Expected output:
#I  Init FRBranchGroupConjugacyData
#I  Finished Init FRBranchGroupConjugacyData
true
# But found:
#I  Init FRBranchGroupConjugacyData
Error, List Element: <list>[1] must have an assigned value
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/fr-2.4.5/tst/cp.tst:73
# Input is:
SetFRBranchGroupConjugacyData(GuptaSidkiGroup,
 rec(initial_conj_dic:=NewDictionary([One(GuptaSidkiGroup),One(GuptaSidkiGroup\
)],true),
    Branchstructure:=BranchStructure(GuptaSidkiGroup),
    RepSystem:=List(~.Branchstructure.group,x->PreImagesRepresentative(~.Branc\
hstructure.quo,x)))
 );
# Expected output:
# But found:
Error, List Element: <list>[1] must have an assigned value
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/fr-2.4.5/tst/cp.tst:78
# Input is:
CallFuncList(function(a,t) 
            local G,D,g,h;
            G:= GuptaSidkiGroup;
            D:= FRBranchGroupConjugacyData(G).initial_conj_dic;
            for g in [a,a^2,t,t^2] do
              for h in [a,a^2,t,t^2] do
               if g<>h then
                AddDictionary(D,[g,h],[]);
               fi;
              od;
            od;
            AddDictionary(D,[a,a],[One(G),a,a^2]);
            AddDictionary(D,[a^2,a^2],[One(G),a,a^2]);
            AddDictionary(D,[t,t],[One(G),,,t,,,t^2]);
            AddDictionary(D,[t^2,t^2],[One(G),,,t,,,t^2]);
          end,GeneratorsOfGroup(GuptaSidkiGroup)
  );
# Expected output:
# But found:
#I  Init FRBranchGroupConjugacyData
Error, List Element: <list>[1] must have an assigned value
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/fr-2.4.5/tst/cp.tst:96
# Input is:
IsConjugate(GuptaSidkiGroup,GuptaSidkiGroup.1^GuptaSidkiGroup.2,GuptaSidkiGrou\
p.1);
# Expected output:
true
# But found:
#I  Init FRBranchGroupConjugacyData
Error, List Element: <list>[1] must have an assigned value
########
```

5. NQ - only when all packages are loaded. This is triggered by loading Semigroups and then LPRES and explained by @fingolfin in https://github.com/gap-packages/cvec/issues/6#issuecomment-394724542.

```
########> Diff in /home/gap/inst/gap-4.9.1/pkg/nq-2.5.3/tst/nq.tst:41
# Input is:
H := NilpotentQuotient( G, 11 );
# Expected output:
Pcp-group with orders [ 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0, 2, 2, 0, 5, 2, 
  2, 2, 3, 0, 5, 5, 2, 2, 2, 2, 3, 0, 5, 5, 2, 2, 2, 2, 2, 2, 3, 0, 0, 5, 5, 
  5 ]
# But found:
Pcp-group with orders [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 5, 6, 5, 4, 0, 5, 
  2, 5, 6, 5, 4, 0, 2, 5, 4, 0, 2, 5, 6, 5, 2, 0 ]
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/nq-2.5.3/tst/nq.tst:125
# Input is:
H := NilpotentQuotient( G, 8 );
# Expected output:
Pcp-group with orders [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 2, 
  2, 3, 3, 0, 6, 2, 2, 2, 3, 3, 6, 2, 3, 6, 2, 2, 2, 2, 3, 3, 3, 2, 2, 3, 3, 
  6, 2 ]
# But found:
Pcp-group with orders [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 3, 0, 
  2, 0, 2, 3, 2, 3, 2, 2, 3, 0, 2, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 3, 2, 2, 2, 
  2, 3, 3, 2, 3, 2, 2, 3, 2, 3 ]
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/nq-2.5.3/tst/nq.tst:150
# Input is:
H := NilpotentQuotient( G, 10 );
# Expected output:
Pcp-group with orders [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 3, 3, 2, 2, 
  0, 0, 3, 3, 3, 2, 2, 2, 2, 0, 0, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 0, 3, 3, 3, 
  3, 3, 3, 3, 2, 2, 2, 5, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 5, 3, 3, 3, 
  3, 3, 3, 3, 3, 3, 3, 3, 3 ]
# But found:
Pcp-group with orders [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 6, 0, 3, 0, 
  6, 0, 3, 3, 2, 3, 36, 0, 2, 3, 3, 3, 2, 2, 3, 90, 3, 6, 0, 3, 2, 3, 3, 3, 
  3, 90, 2, 3, 18, 3, 3, 3, 3, 3, 3, 3, 3, 3 ]
########
```

6. SgpViz - only when all packages are loaded. I have checked and this is triggered after loading the Semigroups package.

```
########> Diff in /home/gap/inst/gap-4.9.1/pkg/SgpViz-0.999.1/tst/testall.tst:
68
# Input is:
f1 := SemigroupFactorization(poi3,el1);
# Expected output:
[ [ Transformation( [ 1, 3, 4, 4 ] ), Transformation( [ 2, 4, 3, 4 ] ) ] ]
# But found:
WARNING: you are possibly using twice the same generator and this may cause pr\
\
oblems...
[ [ Transformation( [ 1, 3, 4, 4 ] ), Transformation( [ 4, 1, 2, 4 ] ) ] ]
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/SgpViz-0.999.1/tst/testall.tst:
70
# Input is:
f1[1][1] * f1[1][2] = el1;
# Expected output:
true
# But found:
false
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/SgpViz-0.999.1/tst/testall.tst:
72
# Input is:
SemigroupFactorization(poi3,[el1,el2]);
# Expected output:
[ [ Transformation( [ 1, 3, 4, 4 ] ), Transformation( [ 2, 4, 3, 4 ] ) ], 
  [ Transformation( [ 2, 4, 3, 4 ] ) ] ]

# But found:
WARNING: you are possibly using twice the same generator and this may cause pr\
\
oblems...
[ [ Transformation( [ 1, 3, 4, 4 ] ), Transformation( [ 4, 1, 2, 4 ] ) ], 
  [ Transformation( [ 2, 4, 3, 4 ] ), Transformation( [ 1, 3, 4, 4 ] ) ] ]
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/SgpViz-0.999.1/tst/testall.tst:
86
# Input is:
DisplayEggBoxOfDClass(D);
# Expected output:
[ [  1,  1,  0,  0 ],
  [  1,  1,  0,  0 ],
  [  0,  0,  1,  1 ],
  [  0,  0,  1,  1 ] ]
# But found:
[ [  1,  0,  1,  0 ],
  [  0,  1,  0,  1 ],
  [  0,  1,  0,  1 ],
  [  1,  0,  1,  0 ] ]
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/SgpViz-0.999.1/tst/testall.tst:
107
# Input is:
rcg := RightCayleyGraphAsAutomaton(b21);
# Expected output:
< deterministic automaton on 2 letters with 6 states >
# But found:
WARNING: you are possibly using twice the same generator and this may cause pr\
\
oblems...
< deterministic automaton on 2 letters with 6 states >
########
```

7. XModAlg - in all three variants of package loading (no/all/default). Presumably this is also triggered by Semigroups, which is in dependencies.

```
########> Diff in /home/gap/inst/gap-4.9.1/pkg/XModAlg-1.16/tst/xmod.tst:117
# Input is:
X1 := XModAlgebra( A, B );
# Expected output:
[Algebra( GF(2), [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f2, (Z(2)^0)*f1+(Z(2)^0\
)*f2, (Z(2)^0)*f2+(Z(2)^0)*f1*f2
 ] )->AlgebraWithOne( GF(2), [ (Z(2)^0)*f1, (Z(2)^0)*f2 ] )]
# But found:
[Algebra( GF(2), [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f1, 
  (Z(2)^0)*f1+(Z(2)^0)*f2, (Z(2)^0)*f2+(Z(2)^0)*f1*f2 
 ] )->AlgebraWithOne( GF(2), [ (Z(2)^0)*f1, (Z(2)^0)*f2 ] )]
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/XModAlg-1.16/tst/xmod.tst:124
# Input is:
X2 := XModAlgebra( C, D );
# Expected output:
[Algebra( GF(2), [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f2, (Z(2)^0)*f1+(Z(2)^0\
)*f2, (Z(2)^0)*f2+(Z(2)^0)*f1*f2
 ] )->AlgebraWithOne( GF(2), [ (Z(2)^0)*f1, (Z(2)^0)*f2 ] )]
# But found:
[Algebra( GF(2), [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f1, 
  (Z(2)^0)*f1+(Z(2)^0)*f2, (Z(2)^0)*f2+(Z(2)^0)*f1*f2 
 ] )->AlgebraWithOne( GF(2), [ (Z(2)^0)*f1, (Z(2)^0)*f2 ] )]
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/XModAlg-1.16/tst/xmod.tst:133
# Input is:
Display( mor );
# Expected output:

Morphism of crossed modules :-
: Source = [Algebra( GF(2), [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f2, (Z(2)^0)\
*f1+(Z(2)^0)*f2,
  (Z(2)^0)*f2+(Z(2)^0)*f1*f2 ] )->AlgebraWithOne( GF(2), [ (Z(2)^0)*f1, (Z(2)^\
0)*f2 ] )] with generating sets:
  [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f2, (Z(2)^0)*f1+(Z(2)^0)*f2, (Z(2)^0)*\
f2+(Z(2)^0)*f1*f2 ]
  [ (Z(2)^0)*<identity> of ..., (Z(2)^0)*f1, (Z(2)^0)*f2 ]
:  Range = [Algebra( GF(2), [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f2, (Z(2)^0)\
*f1+(Z(2)^0)*f2,
  (Z(2)^0)*f2+(Z(2)^0)*f1*f2 ] )->AlgebraWithOne( GF(2), [ (Z(2)^0)*f1, (Z(2)^\
0)*f2 ] )] with generating sets:
  [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f2, (Z(2)^0)*f1+(Z(2)^0)*f2, (Z(2)^0)*\
f2+(Z(2)^0)*f1*f2 ]
  [ (Z(2)^0)*<identity> of ..., (Z(2)^0)*f1, (Z(2)^0)*f2 ]
: Source Homomorphism maps source generators to:
  [ <zero> of ..., <zero> of ..., <zero> of ... ]
: Range Homomorphism maps range generators to:
  [ (Z(2)^0)*<identity> of ..., (Z(2)^0)*<identity> of ..., (Z(2)^0)*<identity\
> of ... ]

# But found:

Morphism of crossed modules :- 
: Source = [Algebra( GF(2), [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f1, 
  (Z(2)^0)*f1+(Z(2)^0)*f2, (Z(2)^0)*f2+(Z(2)^0)*f1*f2 
 ] )->AlgebraWithOne( GF(2), [ (Z(2)^0)*f1, (Z(2)^0)*f2 
 ] )] with generating sets:
  [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f1, (Z(2)^0)*f1+(Z(2)^0)*f2, 
  (Z(2)^0)*f2+(Z(2)^0)*f1*f2 ]
  [ (Z(2)^0)*<identity> of ..., (Z(2)^0)*f1, (Z(2)^0)*f2 ]
:  Range = [Algebra( GF(2), [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f1, 
  (Z(2)^0)*f1+(Z(2)^0)*f2, (Z(2)^0)*f2+(Z(2)^0)*f1*f2 
 ] )->AlgebraWithOne( GF(2), [ (Z(2)^0)*f1, (Z(2)^0)*f2 
 ] )] with generating sets:
  [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f1, (Z(2)^0)*f1+(Z(2)^0)*f2, 
  (Z(2)^0)*f2+(Z(2)^0)*f1*f2 ]
  [ (Z(2)^0)*<identity> of ..., (Z(2)^0)*f1, (Z(2)^0)*f2 ]
: Source Homomorphism maps source generators to:
  [ <zero> of ..., <zero> of ..., <zero> of ... ]
: Range Homomorphism maps range generators to:
  [ (Z(2)^0)*<identity> of ..., (Z(2)^0)*<identity> of ..., 
  (Z(2)^0)*<identity> of ... ]

########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/XModAlg-1.16/tst/xmod.tst:155
# Input is:
X3 := Kernel( mor );
# Expected output:
[Algebra( GF(2), [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f2, (Z(2)^0)*f1+(Z(2)^0\
)*f2, (Z(2)^0)*f2+(Z(2)^0)*f1*f2
 ] )->Algebra( GF(2), [ (Z(2)^0)*f1+(Z(2)^0)*f2, (Z(2)^0)*f1+(Z(2)^0)*f1*f2, (\
Z(2)^0)*<identity> of ...+(Z(2)^0)*f1
 ] )]
# But found:
[Algebra( GF(2), [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f1, 
  (Z(2)^0)*f1+(Z(2)^0)*f2, (Z(2)^0)*f2+(Z(2)^0)*f1*f2 ] )->Algebra( GF(2), 
[ (Z(2)^0)*f1+(Z(2)^0)*f2, (Z(2)^0)*f1+(Z(2)^0)*f1*f2, 
  (Z(2)^0)*<identity> of ...+(Z(2)^0)*f1 ] )]
########
########> Diff in /home/gap/inst/gap-4.9.1/pkg/XModAlg-1.16/tst/xmod.tst:169
# Input is:
Print( MappingGeneratorsImages( theta ), "\n" ); 
# Expected output:
[ [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f2, (Z(2)^0)*f1+(Z(2)^0)*f2, 
      (Z(2)^0)*f2+(Z(2)^0)*f1*f2 ], 
  [ <zero> of ..., <zero> of ..., <zero> of ... ] ]
# But found:
[ [ (Z(2)^0)*<identity> of ...+(Z(2)^0)*f1, (Z(2)^0)*f1+(Z(2)^0)*f2, 
      (Z(2)^0)*f2+(Z(2)^0)*f1*f2 ], 
  [ <zero> of ..., <zero> of ..., <zero> of ... ] ]
########
```

**Comment by olexandr-konovalov** [comment]
I have now understand what happened with packages where diffs are triggered by the presence of the Semigroups package. Prior to the update of the Docker container, the version of gcc there was too old and semigroups refused to build. Now it is built successfully, and problems became visible.

**Comment by olexandr-konovalov** [comment]
For FR, the full error message in the break loop (when all packages are loaded) is:
```
gap> IsConjugate(GrigorchukGroup,pairs[1][1][1],pairs[1][1][2]);
#I  Init FRBranchGroupConjugacyData
Error, List Element: <list>[1] must have an assigned value in
  return WreathProductInfo( W ).embeddings[i]; at /home/gap/inst/gap-4.9.1/pkg/rcwa-4.6.1/lib/rcwagrp.gi:2794 called from 
Embedding( W, i ) at /home/gap/inst/gap-4.9.1/pkg/fr-2.4.5/gap/group.gi:2800 called from
func( C[1] ) at /home/gap/inst/gap-4.9.1/lib/coll.gi:1283 called from
CallFuncList( CAP_INTERNAL_PRODUCT_SAVE, arg ) at /home/gap/inst/gap-4.9.1/pkg/CAP-2017.09.25/gap/ProductCategory.gi:526 called from
Product( set, function ( i )
      return (d[1][i] ^ pi) ^ Embedding( W, i );
  end ) at /home/gap/inst/gap-4.9.1/pkg/fr-2.4.5/gap/group.gi:2800 called from
BranchStructure( G ) at /home/gap/inst/gap-4.9.1/pkg/fr-2.4.5/gap/cp.gi:736 called from
...  at *stdin*:26
you can 'return;' after assigning a value
brk> 
```
Note that a similar error appears in https://github.com/gap-packages/loops/issues/2

**Comment by olexandr-konovalov** [comment]
Another diff can now be seen at https://travis-ci.org/gap-system/gap-docker-master-testsuite/jobs/388272559: when all packages are loaded, testbugfix has two diffs:
```
########> Diff in /home/gap/inst/gap-master/tst/testbugfix/2018-05-09-submagma\
.tst:33
# Input is:
mgm:=Magma( () );
# Expected output:
<commutative semigroup with 1 generator>
# But found:
<trivial group with 1 generator>
########
########> Diff in /home/gap/inst/gap-master/tst/testbugfix/2018-05-09-submagma\
.tst:41
# Input is:
IsMagmaWithInverses(mgm);
# Expected output:
false
# But found:
true
########
```

**Comment by olexandr-konovalov** [comment]
The latter problem with `testbugfix` is triggered by the Semigroups package and reported to @james-d-mitchell at https://github.com/gap-packages/Semigroups/issues/492

**Comment by olexandr-konovalov** [comment]
Checked and ticked FR and NQ boxes above - see https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9/builds/424606062

**Comment by olexandr-konovalov** [comment]
xmodalg fixed. Cryst and SgpViz remain open - see https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.10 and https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.10-staging for the latest status of the tests.

**Comment by olexandr-konovalov** [comment]
cryst fixed. waiting for @manuelafdelgado to fix https://github.com/gap-packages/sgpviz/issues/3.

**Comment by olexandr-konovalov** [comment]
Everything resolved by now.
